import { Unbounded, Sora } from "next/font/google";
import "./globals.css";
//icon
import 'remixicon/fonts/remixicon.css'
import Nav from "./Components/Nav";
import Footer from "./Components/Footer";


const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  width:['400','500','600','700']
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
    width:['400','500','600','700']
});

export const metadata = {
  title: "Ceylon Travels",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${sora.variable} ${unbounded.variable} antialiased flex flex-col min-h-screen`}
      >
        <Nav/>
        <div className="flex-grow">
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
